name: example
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  anadea_flutter_loggy:
    path: ../
  loggy: ^2.0.1+1
  flutter_loggy: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
